### ISSUE TITLE
Best way of accessing invalid values with progressive enhancement in mind

### ISSUE THREAD

**Issue by gbouteiller** [IdoPesok/zsa#102]
In the context of using `input` with `type="state"` and invalid values with progressive enhancement in mind, is there a way of getting these (invalid) values to pass it for instance as `defaultValues` in `RHF` (in that way, the form can be filled with the values during server rendering even if javascript is disabled)?

actions.ts
```typescript
"use server"

export const subscribeToNewsletterAction = createServerAction()
  .input(zNewsletterValues, {type: "state"})
  .handler(async ({input: {email}}) => subscribeToNewsletter(email))
``` 

newsletter-form.tsx
```typescript
"use client"

export default function NewsletterForm() {
  const [[data, error], action, pending] = useActionState(subscribeToNewsletterAction, [null, null])

 const form = useForm<NewsletterValues>({
    mode: "onTouched",
    resolver: zodResolver(zNewsletterValues),
    defaultValues: ... // error?.values or similar
  })

``` 

For now, my workaround is to create an extra function like the one in `custom state` when I can access `formData` directly and pass it through:

actions.ts
```typescript
"use server"

const subscribeToNewsletterZSA = createServerAction()
  .input(zNewsletterValues, {type: "state"})
  .handler(async ({input: {email}}) => subscribeToNewsletter(email))

export const subscribeToNewsletterAction = async (
  _prev: NewsletterState,
  formData: FormData
): Promise<NewsletterState> => {
  const [data, error] = await subscribeToNewsletterZSA(formData)
  if (data) return [data, null] 
  const values = Object.fromEntries(formData.entries()) as NewsletterValues
  return [null, {...error, values}]
}

```

**Comment by IdoPesok** [comment]
Hi, thank you for this suggestion. I am on board with this. This will most likely be merged in with `shapeError`.

Here is a quick update of what it will look like:

<img width="408" alt="Screen Shot 2024-06-07 at 4 41 08 PM" src="https://github.com/IdoPesok/zsa/assets/43461847/41fd1018-4738-4fea-8d52-df20083b4a3d">

This was incredibly tricky to get the types to align, but there is progress! The problem here is that most people will likely put their shape errors function in procedures. In doing that, there is no way to actually type the errors correctly with the correct zod schema. Why? Because the zod schemas will most likely get defined in the actions -- which the procedure doesn't have types for.

It was incredibly important for me that even if you define shape error in a procedure, your errors will still be typed based on the final schema defined in your action. Happy to report, it is (somewhat) working! As you can see in the image, the final error type is a combination of the procedure input and action input -- even though the procedure never has access to the action types. Users will need to use a `typedData` object when passing forward these types.

Looking for feedback before it gets merged!

**Comment by gbouteiller** [comment]
Yes, I understand what you mean, types at that level can be really tricky 😄 but the result looks really promising. Awesome job!

**Comment by IdoPesok** [comment]
Give it a shot with `zsa@0.3.4`! [Documentation](https://zsa.vercel.app/docs/shape-errors)

**Comment by gbouteiller** [comment]
Hello @IdoPesok , 
I just wanted to show you the code, it works perfectly! Thank you so much.

actions.ts
```typescript
"use server"

export const formAction = createServerActionProcedure()
  .experimental_shapeError(({err, typedData}) => {
    const values = Object.fromEntries(Object.entries(typedData.inputRaw).filter(([name]) => !name.startsWith("$ACTION")))
    if (!(err instanceof ZSAError)) return {code: "INTERNAL_SERVER_ERROR" as const, errors: {root: {type: "INTERNAL_SERVER_ERROR"}}, values}
    const {code, inputParseErrors, message} = err
    const errors = {
      root: {type: code, message: message ?? inputParseErrors?.formErrors?.[0]},
      ...Object.fromEntries(Object.entries(inputParseErrors?.fieldErrors ?? {}).map(([name, errors]) => [name, {message: errors?.[0]}])),
    }
    return {code, errors, values}
  })
  .handler(() => {})
  .createServerAction()

export const subscribeToNewsletterAction = formAction
  .experimental_shapeError(({ctx: {code, errors, values}}) => (code === "CONFLICT" ? {code, errors} : {code, errors, values}))
  .input(zNewsletterValues, {type: "state"})
  .output(z.boolean())
  .handler(async ({input: {email}}) => {
    const code = await subscribeToNewsletter(email)
    if (code !== "SUCCESS") throw new ZSAError(code)
    return true
  })
``` 

newsletter-form.tsx
```typescript
"use client"

export default function NewsletterForm() {
  const [[success, failure], action, pending] = useActionState(subscribeToNewsletterAction, [null, null])

  const form = useForm<NewsletterValues>({
    mode: "onTouched",
    resolver: zodResolver(zNewsletterValues),
    defaultValues: failure?.values ?? defaultNewsletterValues,
    errors: failure?.errors,
  })
```

**Comment by IdoPesok** [comment]
Awesome -- happy to hear!! Code looks great.
