### ISSUE TITLE
Invalid opts, must originate from the server

### ISSUE THREAD

**Issue by blechatellier** [IdoPesok/zsa#179]
I'm getting the error "Invalid opts, must originate from the server" when generating the specs from the server, most likely a change in my code but I can't figure out the reason. When would this error happen please?

**Comment by IdoPesok** [comment]
Hi, what versions of zsa are you on?

**Comment by blechatellier** [comment]
I'm on the latest,
```
    "zsa": "0.5.0",
    "zsa-openapi": "0.3.0",
    "zsa-react": "0.2.2"
```

Not sure if related but for some reasons all my endpoint return a 200 empty object `{}`, even if I revert to the previous versions, trying to replicate the issue.

**Comment by IdoPesok** [comment]
Copy, the reason why this happens is `zsa` makes sure that the client cannot manipulate the options argument in action handlers. This is the second/third argument that holds some internal state when being called with procedure chains, retries, etc. To check, the options argument must always contain a source key with the value being a class that has a function that returns true - since clients can't send a class like this over the network.

- [Handler Options](https://github.com/IdoPesok/zsa/blob/5e1fbc7dc8221ad9c1d97cf751c3e80031822fd5/packages/zsa/src/types.ts#L119)
- [Options Validation](https://github.com/IdoPesok/zsa/blob/5e1fbc7dc8221ad9c1d97cf751c3e80031822fd5/packages/zsa/src/zod-safe-function.ts#L44)

**Comment by IdoPesok** [comment]
I can't seem to reproduce the empty object returning. Interesting how it is still happening when you revert.

**Comment by blechatellier** [comment]
I've deleted the dependencies and re-installed them and everything seems to work again. Will close and keep an eye if this happens again. Thanks @IdoPesok
